[package]
name = "chapterverse"
version = "2024.2.15"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "^0.1.77"
colored = { version = "2.1.0", features = ["no-color"] }
crossterm = "^0.27.0"
csv = "1.3.0"
dotenv = "^0.15.0"
fern = "0.6.2"
humantime = "2.1.0"
log = "0.4.20"
reqwest = { version = "^0.11.24", features = ["json"] }
serde = { version = "^1.0.196", features = ["derive"] }
serde_json = "^1.0.113"
strum = "^0.26.1"
strum_macros = "^0.26.1"
tokio = "^1.36.0"


