[package]
name = "chapterverse"
version = "2024.2.15"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "lib/bible",
    "lib/twitch",
]


[dependencies]
bible = { path = "lib/bible" }
twitch = { path = "lib/twitch" }
async-trait = "^0.1.77"
crossterm = "^0.27.0"

dotenv = "^0.15.0"
reqwest = { version = "^0.11.24", features = ["json"] }
strum = "^0.26.1"
strum_macros = "^0.26.1"
tokio = "^1.36.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bible_benchmark"
harness = false